version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    environment:
      PORT: 3001
    command: -- ./node_modules/.bin/nodemon --watch ./ --ignore test/ index.js
    volumes:
      - ./src:/usr/src/app

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
