version: "3.7"
services:
  web:
    build: ./
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      PORT: 3001
    command: -- ./node_modules/.bin/nodemon --watch src --ignore test/ index.js
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config

  web_test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      PORT: 3001
    volumes:
      - ./test:/usr/src/app/test
      - ./config:/usr/src/app/config

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  default:
    driver: bridge