GET http://localhost:3001/

###

POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "email@email.com",
  "firstname": "Zdziław",
  "lastname": "Koń",
  "password": "@11!"
}

###

POST http://localhost:3001/register
Content-Type: application/json

{
  "email": "email@email.com",
  "firstname": "Zdziław",
  "lastname": "Koń",
  "password": "@11!"
}

###

GET http://localhost:3001/users
